### ISSUE TITLE
Add multi-gamepad support.

### ISSUE THREAD

**Issue by zerofalcon** [capitalistspz/gamepadtopro#1]
Hi and first of all thank you for your aroma plugin. I already tested it and works perfectly.

Ok this is not really an issue but more like a suggestion/petition (sorry about that). Do you think the code to add multi-gamepad support can be added to your plugin? this way, two gamepads could be used as a wii u pro controller. Retroarch for Wii U already its coded to support two gamepads individually (I made some tests and works pretty good). We can pair and use both Wii U gamepads using the system config tool while using the multiDRC support. 

The code is here: 
https://github.com/libretro/RetroArch/pull/10646

Thanks in advanced and sorry if this is out of scope, just was an idea I just have while testing your plugin.

**Comment by capitalistspz** [comment]
done

**Comment by zerofalcon** [comment]
Wow you did it! thank you again. I just played mario kart 8, just minutes ago, and is working great no issues so far.
