### ISSUE TITLE
Channel Configuration Issues

### ISSUE THREAD

**Issue by Knkaku** [capitalistspz/gamepadtopro#2]
Once you change the channel to 1 or higher, you cannot change it back to 0 again unless you delete the configuration file or make a physical change.

**Comment by capitalistspz** [comment]
> Once you change the channel to 1 or higher, you cannot change it back to 0 again unless you delete the configuration file or make a physical change.

Try this, https://github.com/capitalistspz/gamepadtopro/releases/tag/1.1.1

**Comment by Knkaku** [comment]
Thank you! Also, I would like to ask you to add a function. Normally, pairing two GamePads is done with the System Config Tool, but this is inconvenient and there is a possibility that other settings may be tampered with, which is dangerous. So, can you add the pairing function for two GamePads as this plugin or another plugin or app?

**Comment by capitalistspz** [comment]
Did the update fix the config issue?

**Comment by capitalistspz** [comment]
And in regards to pairing multiple GamePads, try https://github.com/capitalistspz/pairingtest/releases
I only have one GamePad, so I can't test it properly

**Comment by Knkaku** [comment]
Yes, the problem is solved.
However, the pairingtest you gave me didn't work at all.
